config/routes.rb
Rails.application.routes.draw do
  root 							'flights#index'
  get  'flights' => 'flights#index'

	resources :bookings,     only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departing_flights, foreign_key: :starting_airport_id, 		class_name: "Flight"
	has_many :arriving_flights,  foreign_key: :finishinging_airport_id, class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :flight
	has_many :passengers
	accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :starting_airport,  foreign_key: "starting_airport_id",	class_name: "Airport"
  belongs_to :finishing_airport, foreign_key: "finishing_airport_id", class_name: "Airport"
  has_many :bookings

  def flight_date_formatted
  	departure_time.strftime("%m/%d/%Y")
  end

  def departure_time_formatted
  	departure_time.strftime("%m/%d/%Y @ %H:%M")
  end

  def arrival_time_formatted
  	arrival_time.strftime("%m/%d/%Y @ %H:%M")
  end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
  	@booking = Booking.new()
  	@flight_id = params[:flight_id]
  	@number_of_passengers = params[:number_of_passengers]
  	params[:number_of_passengers].to_i.times { @booking.passengers.build }
  end

  def create
  	@booking = Booking.new(booking_params)
  	if(@booking.save)
      @booking.passengers.each do |passenger|
        PassengerMailer.thank_you_email(passenger).deliver_later
      end
  		render 'show'
  	else
  		redirect_to root_url
  	end
  end

  def show
  	@booking = Booking.find(params[:id])
  end

  private

  def booking_params
  	params.require(:booking).permit(:flight_id, :number_of_passengers, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  	@airports = Airport.all
  	@flight_times = Flight.select(:departure_time).distinct
  	@matching_flights = Flight.where(starting_airport: params[:departure_airport],
  																		 finishing_airport: params[:arrival_airport])
  	@num_of_passengers = params[:number_of_passengers]
  end

  def search_params
  	params.permit(:departure_airport, :arrival_airport, :number_of_passengers, :flight_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<h1>Finalize your booking</h1>

<%= form_for(@booking, url: bookings_path) do |f| %>
	<ul>
		<%= f.hidden_field :flight_id, value: @flight_id %>
		<%= f.hidden_field :number_of_passengers, value: @number_of_passengers %>
		<%= f.fields_for :passengers do |passenger_form| %>
			<li>
				<%= passenger_form.label :name %>
				<%= passenger_form.text_field :name %>

				<%= passenger_form.label :email %>
				<%= passenger_form.text_field :email %>
			</li>
		<% end %>
	</ul>
	<%= f.submit "Finalize booking" %>
<% end %>	

app/views/bookings/show.html.erb
<h1>Your Booking</h1>

<p>From: <%= @booking.flight.starting_airport.airport_code %> @ <%= @booking.flight.departure_time %></p>
<p>To: <%= @booking.flight.finishing_airport.airport_code %> @ <%= @booking.flight.arrival_time %></p>
<p>Passengers:</p>
<ul>
	<% @booking.passengers.each do |passenger| %>
		<li><%= passenger.name %></li>
	<% end %>
</ul>

app/views/flights/index.html.erb
<h1>Search for a flight</h1>

<%= form_tag("/flights", method: "get") do %>
	<%= label_tag :departure_airport, "From" %>
	<%= select_tag(:departure_airport, options_from_collection_for_select(@airports, :id, :airport_code)) %>
	
	<%= label_tag :arrival_airport, "To" %>
	<%= select_tag(:arrival_airport, options_from_collection_for_select(@airports, :id, :airport_code)) %>

	<%= label_tag :number_of_passengers, "Number of passengers" %>
	<%= select_tag(:number_of_passengers, options_for_select([[1,1],[2,2],[3,3],[4,4]])) %>

	<%= label_tag :flight_date, "Date" %>
	<%= select_tag(:flight_date, options_from_collection_for_select(@flight_times, 'departure_time', :flight_date_formatted)) %>

	<%= submit_tag("Search") %>
<% end %>

<% if @matching_flights.any? %> 
	<h1>Matching Flights</h1>

	<table>
		<thead>
			<tr>
				<td></td>
				<td>From</td>
				<td>To</td>
				<td>Leaves</td>
				<td>Arrives</td>
			</tr>
		</thead>
		<%= form_tag("/bookings/new", method: "get") do %>
			<% @matching_flights.each do |flight| %>
				<tr>
					<td><%= radio_button_tag(:flight_id, flight.id) %></td>
					<td><%= flight.starting_airport.airport_code %></td>
					<td><%= flight.finishing_airport.airport_code %></td>
					<td><%= flight.departure_time_formatted %></td>
					<td><%= flight.arrival_time_formatted %></td>
				</tr>
			<% end %>
		</table>
		<%= hidden_field_tag(:number_of_passengers, @num_of_passengers) %>	
		<%= submit_tag("Book your flight") %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>